### ISSUE TITLE
Apple Music lyrics not match

### ISSUE THREAD

**Issue by ianz56** [tomakino/CSLyric#10]
The lyrics on the Apple Music player often don't match, i.e. they're different from what's playing, they're often from a previously played song or a song in my library.
![IMG_20241004_025736](https://github.com/user-attachments/assets/574d5f3f-00e2-4cfa-bad7-72ac7143234e)
![IMG_20241004_025653](https://github.com/user-attachments/assets/d75650d0-cc88-48da-8007-39bec76684f2)

**Comment by tomakino** [comment]
https://github.com/tomakino/CSLyric/releases/tag/v3.0-beta3
