### ISSUE TITLE
请求洛雪音乐的适配

### ISSUE THREAD

**Issue by langkiss** [tomakino/CSLyric#12]
这种软件还是挺好用的，可惜落雪只支持桌面歌词太丑了，大佬有没有好办法，获取歌词到状态栏就行

**Comment by tomakino** [comment]
0.2.7-bate测试版本支持
https://github.com/tomakino/CSLyric/releases/tag/0.2.7-bate

**Comment by langkiss** [comment]
> 0.2.7-bate测试版本支持 https://github.com/tomakino/CSLyric/releases/tag/0.2.7-bate

已试用，超级好用
![Uploading Screenshot_2024-10-20-20-28-27-670_com.tencent.mobileqq.png…]()
