### ISSUE TITLE
无法激活

### ISSUE THREAD

**Issue by EAlZZZl** [tomakino/CSLyric#20]
![Screenshot_20241026-203939.png](https://github.com/user-attachments/assets/5fb0bf14-cbce-48f2-9b8c-ea6f1cfddbbe)

![Screenshot_20241026-202240.png](https://github.com/user-attachments/assets/e8532d79-665a-408c-8fb4-5573fbfc8a46)

忘加bug标签了，还无法删除？

**Comment by tomakino** [comment]
没提供log，无法修复

**Comment by EAlZZZl** [comment]
怎么导出日志？


________________________________
发件人: Makino ***@***.***>
发送时间: 星期四, 十月 31, 2024 7:29:45 下午
收件人: tomakino/CSLyric ***@***.***>
抄送: EAlZZZl ***@***.***>; Author ***@***.***>
主题: Re: [tomakino/CSLyric] 无法激活 (Issue #20)


没提供log，无法修复

―

**Comment by tomakino** [comment]
可能是lsposed的问题，你手机上其它模块能用吗?

**Comment by EAlZZZl** [comment]
能

________________________________
发件人: Makino ***@***.***>
发送时间: 2024年11月3日 19:25
收件人: tomakino/CSLyric ***@***.***>
抄送: EAlZZZl ***@***.***>; Author ***@***.***>
主题: Re: [tomakino/CSLyric] 无法激活 (Issue #20)


可能是lsposed的问题，你手机上其它模块能用吗?

―
