### ISSUE TITLE
［FR］动态歌词滚动速度

### ISSUE THREAD

**Issue by LINKlang** [tomakino/CSLyric#25]
现在当歌词宽度变窄的时候，歌词来不及滚动完就消失换下一个了，希望加入动态滚动时间，根据歌词长度和到下一个歌词的时间间隔调整滚动速度

**Comment by LINKlang** [comment]
@tomakino 佬看你重新更新了，想问一下有没有重新适配的打算

**Comment by tomakino** [comment]
> [@tomakino](https://github.com/tomakino) 佬看你重新更新了，想问一下有没有重新适配的打算

部分软件hook得到的歌词为纯文本，不包含时间内容，无法完全适配。

**Comment by LINKlang** [comment]
> > [@tomakino](https://github.com/tomakino) 佬看你重新更新了，想问一下有没有重新适配的打算
> 
> 部分软件hook得到的歌词为纯文本，不包含时间内容，无法完全适配。

针对性适配呢，给某些软件开放

**Comment by LINKlang** [comment]
> 无法完全适配

等下，佬是已经在 1.2 中适配了一些软件了吗，实时歌词指的是动态速度歌词吗

**Comment by tomakino** [comment]
> > 无法完全适配
> 
> 等下，佬是已经在 1.2 中适配了一些软件了吗，实时歌词指的是动态速度歌词吗

是的
