### ISSUE TITLE
能适配OPPO流体云吗

### ISSUE THREAD

**Issue by DuckDeng** [tomakino/CSLyric#27]
OPPO流体云用于暂停、播放很方便，但当流体云展开时，会直接覆盖在歌词之上，当流体云收起到摄像头孔时，歌词正常。

可行的方案
- 在流体云展开时调整歌词宽度（增加一个专门针对流体云展开时的宽度选项）

![image](https://github.com/user-attachments/assets/b5891307-ec90-4a1e-8b29-67c19ac89dab)
![image](https://github.com/user-attachments/assets/4539ba4f-4ab0-4e74-b0be-9f27d6093967)

**Comment by tomakino** [comment]
可不可以直接隐藏`流体云`

**Comment by LINKlang** [comment]
我的做法是靠调整歌词宽度，手动调完后就好了，反正只要播放音乐流体云媒体组件就会出现的

**Comment by DuckDeng** [comment]
> 可不可以直接隐藏`流体云`

可以收起到摄像头孔，但隐藏之后就无法使用流体云的播放控制了

**Comment by tomakino** [comment]
OK，我升级到了最新版本系统，现在有条件可以优化这个问题。

**Comment by tomakino** [comment]
> > 我的做法是靠调整歌词宽度，手动调完后就好了，反正只要播放音乐流体云媒体组件就会出现的
> 
> 手动调整，展开和收起状态的宽度是固定的，我想要的是，在展开状态自动变窄，收起状态自动变宽。我不想使流体云直接失效啊

OK，我升级到了最新版本系统，现在有条件可以优化这个问题。
