### ISSUE TITLE
Apple music 4.8.0(1393) 切换下一首时歌词不加载

### ISSUE THREAD

**Issue by dongguaguaguagua** [tomakino/CSLyric#43]
### Describe the bug

Similar Issue：https://github.com/xiaowine/Lyric-Getter/issues/87

- 当Apple Music处于足够旧版本时，例如1298，则不存在这个问题。所以问题的本质是“Apple Music更新后，歌词不会在播放音乐时一并下载，而是等用户点击音乐后（音乐处于全屏状态下）才开始下载“。
- 症状描述1：一首歌不点开时，状态栏歌词不会加载。
- 症状描述2：当Apple Music自动切换下一曲时，歌词也不会自动加载。但是我只要切换回Apple Music，点击歌曲并加载出来歌词，就又有状态栏歌词了。

### To Reproduce

- 下载 Apple music 4.8.0(1393)
- 安装最新版[CSLyric (v3.0-beta)](https://github.com/tomakino/CSLyric/releases/tag/v3.0-beta)
- 等一首歌播完
- 状态栏歌词消失或仍然是上一曲的歌词
- 切回Apple Music，点击在播歌曲，加载歌词
- 状态栏歌词出现

Expected behavior

像网易云一样，自动加载并在状态栏显示下一首歌的歌词。

**Comment by tomakino** [comment]
https://github.com/tomakino/CSLyric/releases/tag/v3.0-beta3
