### ISSUE TITLE
一段时间未播放音乐后无法显示歌词

### ISSUE THREAD

**Issue by windy1021** [tomakino/CSLyric#5]
必须重启系统界面或者锁屏再解锁才能重新显示，我是color14系统，也有看到MIUI遇到相同情况的，虽然不是不能用，但是如果可以希望再优化一下，辛苦~

**Comment by windy1021** [comment]
抱歉，排查出来了，是我用了伞姨的美化模块导致的

**Comment by windy1021** [comment]
发现关闭在锁屏页面隐藏就好了，是bug吗还是我对这个选项理解错误了🥲

**Comment by tomakino** [comment]
> 发现关闭在锁屏页面隐藏就好了，是bug吗还是我对这个选项理解错误了🥲

是bug😓
